apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - name: udagram-api-user
        image: docker.io/kellyobende/udagram-api-user:v5a
        ports:
        - containerPort: 8080
        resources:
           requests:
             memory: "1024Mi"
             cpu: 500m
           limits:
             memory: "2092Mi"
             cpu : 1000m
       