apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy  
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: docker.io/kellyobende/reverseproxy:v5a
        ports:
        - containerPort: 8080
        resources:
           requests:
             memory: "1024Mi"
             cpu: "1"
           limits:
             memory: "8192Mi"
             cpu : "2"
      
        